version: '3.7'

services:
  our-db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=master
      - POSTGRES_PASSWORD=master
      - POSTGRES_DB=MASTER
    restart: unless-stopped
    ports:
      - "5432:5432"