app:
  db1:
    url: jdbc:postgresql://localhost:5432/MASTER
    username: master
    password: master
  db2:
    url: jdbc:clickhouse://localhost:8125
    username: default
    password: ""


spring:
  datasource:
    url: ${app.db1.url}
    username: ${app.db1.username}
    password: ${app.db1.password}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    io.ebean.*: TRACE